name: AutoUpdate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0/2 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: setup py
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: update versions.json
        run: |
          cd ${{ github.workspace }}
          if [ `python3 main.py | grep need | wc -l` -ne 0 ]; then
            python3 main.py
            git add -A
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "auto update"
            git push
          fi
